<cfset aMenu = []>
<cfset aMenu[1][1] = "Home">
<cfset aMenu[1][2] = "/">
<cfset aMenu[1][3] = "">
<cfset aMenu[1][4] = "">
<cfset aMenu[1][5] = []>
<cfset aMenu[2][1] = "Search">
<cfset aMenu[2][2] = "/default.cfm/page/forsale/searchby/list/propertytype/residential.htm">
<cfset aMenu[2][3] = "">
<cfset aMenu[2][4] = "">
<cfset aMenu[2][5] = []>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Residential">
<cfset aMenuItem[2] = "/default.cfm/page/forsale/searchby/list/propertytype/residential.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[2][5][1] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Multi Family">
<cfset aMenuItem[2] = "/default.cfm/page/forsale/searchby/list/propertytype/multifamily.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[2][5][2] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Commercial">
<cfset aMenuItem[2] = "/default.cfm/page/forsale/searchby/list/propertytype/commercial.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[2][5][3] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Land">
<cfset aMenuItem[2] = "/default.cfm/page/forsale/searchby/list/propertytype/land.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[2][5][4] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Single Family Homes">
<cfset aMenuItem[2] = "/default.cfm/page/forsale/searchby/list/propertytype/residential/res_style/detachd">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[2][5][5] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Condos and Townhomes">
<cfset aMenuItem[2] = "/default.cfm/page/forsale/searchby/list/propertytype/residential/res_style/con.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[2][5][6] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Manufactured Homes">
<cfset aMenuItem[2] = "/default.cfm/page/forsale/searchby/list/propertytype/residential/res_style/man.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[2][5][7] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Recently Reduced Properties">
<cfset aMenuItem[2] = "/default.cfm/page/forsale/searchby/list/propertytype/residential/newdays/7.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[2][5][8] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Recently Listed Properties">
<cfset aMenuItem[2] = "/default.cfm/page/forsale/searchby/list/propertytype/residential/newdays/7.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[2][5][9] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Foreclosures">
<cfset aMenuItem[2] = "/default.cfm/page/forsale/searchby/list/propertytype/residential/resale/f/reo/t/shortsale/f.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[2][5][10] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Short Sales">
<cfset aMenuItem[2] = "http://www.fault.cfm/page/forsale/searchby/list/propertytype/residential/resale/f/reo/f/shortsale/t.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[2][5][11] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Previews Homes">
<cfset aMenuItem[2] = "/default.cfm/page/forsale/searchby/list/propertytype/residential/previews/t.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[2][5][12] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "New Construction">
<cfset aMenuItem[2] = "/default.cfm/page/forsale/searchby/list/propertytype/residential/Subtype/new%20construction.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[2][5][13] = aMenuItem>
<cfset aMenu[3][1] = "Buyers">
<cfset aMenu[3][2] = "/default.cfm/page/buyers.htm">
<cfset aMenu[3][3] = "">
<cfset aMenu[3][4] = "">
<cfset aMenu[3][5] = []>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Buyers">
<cfset aMenuItem[2] = "/default.cfm/page/buyers/cat/home.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[3][5][1] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Buyers Services Guarantee">
<cfset aMenuItem[2] = "/default.cfm/page/buyers/cat/guarantee.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[3][5][2] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Just Listed Nashville">
<cfset aMenuItem[2] = "/default.cfm/page/buyers/cat/just_listed_nashville.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[3][5][3] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Coldwell Banker on Location">
<cfset aMenuItem[2] = "http://www.youtube.com/coldwellbanker">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[3][5][4] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Find a Realtor">
<cfset aMenuItem[2] = "/default.cfm/page/agent.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[3][5][5] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Find an Office">
<cfset aMenuItem[2] = "/default.cfm/page/offices.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[3][5][6] = aMenuItem>
<cfset aMenu[4][1] = "Sellers">
<cfset aMenu[4][2] = "/default.cfm/page/sellers.htm">
<cfset aMenu[4][3] = "">
<cfset aMenu[4][4] = "">
<cfset aMenu[4][5] = []>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Sellers">
<cfset aMenuItem[2] = "/default.cfm/page/sellers/cat/home.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[4][5][1] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Our Sellers Guarantee">
<cfset aMenuItem[2] = "/default.cfm/page/sellers/cat/guarantee.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[4][5][2] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "What is Your Sign">
<cfset aMenuItem[2] = "/default.cfm/page/sellers/cat/whats_your_sign.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[4][5][3] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Just Listed Nashville">
<cfset aMenuItem[2] = "/default.cfm/page/sellers/cat/just_listed_nashville.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[4][5][4] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Find a Realtor">
<cfset aMenuItem[2] = "/default.cfm/page/agent.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[4][5][5] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Find an Office">
<cfset aMenuItem[2] = "/default.cfm/page/offices.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[4][5][6] = aMenuItem>
<cfset aMenu[5][1] = "Open Houses">
<cfset aMenu[5][2] = "/default.cfm/page/forsale/searchby/list/openhouse/t.htm">
<cfset aMenu[5][3] = "">
<cfset aMenu[5][4] = "">
<cfset aMenu[5][5] = []>
<cfset aMenu[6][1] = "Relocation">
<cfset aMenu[6][2] = "/default.cfm/page/relocation.htm">
<cfset aMenu[6][3] = "">
<cfset aMenu[6][4] = "">
<cfset aMenu[6][5] = []>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Relocation Services">
<cfset aMenuItem[2] = "/default.cfm/page/relocation/cat/home.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[6][5][1] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Corporate Relocation">
<cfset aMenuItem[2] = "/default.cfm/page/relocation/cat/corporate.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[6][5][2] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "REO and Foreclosure Services">
<cfset aMenuItem[2] = "/default.cfm/page/relocation/cat/reo_forclosure.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[6][5][3] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Personal and Family Relocation">
<cfset aMenuItem[2] = "/default.cfm/page/relocation/cat/personal.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[6][5][4] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Relocating outside of Nashville">
<cfset aMenuItem[2] = "/default.cfm/page/relocation/cat/relocating_outside.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[6][5][5] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Meet our Relocation Team">
<cfset aMenuItem[2] = "/default.cfm/page/relocation/cat/relocation_team.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[6][5][6] = aMenuItem>
<cfset aMenu[7][1] = "Services">
<cfset aMenu[7][2] = "/default.cfm/page/sellers/cat/home.htm">
<cfset aMenu[7][3] = "">
<cfset aMenu[7][4] = "">
<cfset aMenu[7][5] = []>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Selling a Home">
<cfset aMenuItem[2] = "/default.cfm/page/sellers/cat/home.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[7][5][1] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Buying a Home">
<cfset aMenuItem[2] = "/default.cfm/page/buyers/cat/home.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[7][5][2] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Relocation Services">
<cfset aMenuItem[2] = "/default.cfm/page/relocation.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[7][5][3] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Mortgage Services">
<cfset aMenuItem[2] = "/default.cfm/page/mortgage.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[7][5][4] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Title Services">
<cfset aMenuItem[2] = "http://www.http://www.http://www.summitlandtitle.com/">
<cfset aMenuItem[3] = "_blank">
<cfset aMenuItem[4] = "">
<cfset aMenu[7][5][5] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Concierge Services">
<cfset aMenuItem[2] = "/default.cfm/page/concierge.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[7][5][6] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Auctions">
<cfset aMenuItem[2] = "http://www.coldwellbankerauctions.com/">
<cfset aMenuItem[3] = "_blank">
<cfset aMenuItem[4] = "">
<cfset aMenu[7][5][7] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Find a Realtor">
<cfset aMenuItem[2] = "/default.cfm/page/agent.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[7][5][8] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Find an Office">
<cfset aMenuItem[2] = "/default.cfm/page/offices.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[7][5][9] = aMenuItem>
<cfset aMenu[8][1] = "Agents">
<cfset aMenu[8][2] = "/default.cfm/page/agent.htm">
<cfset aMenu[8][3] = "">
<cfset aMenu[8][4] = "">
<cfset aMenu[8][5] = []>
<cfset aMenu[9][1] = "About Us">
<cfset aMenu[9][2] = "/default.cfm/page/about_us/cat/home.htm">
<cfset aMenu[9][3] = "">
<cfset aMenu[9][4] = "">
<cfset aMenu[9][5] = []>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "About our Company">
<cfset aMenuItem[2] = "/default.cfm/page/about_us/cat/home.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[9][5][1] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Our Blog">
<cfset aMenuItem[2] = "/default.cfm/page/blog.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[9][5][2] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "What our Customers Say">
<cfset aMenuItem[2] = "/default.cfm/page/about_us/cat/customers.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[9][5][3] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Awards">
<cfset aMenuItem[2] = "/default.cfm/page/about_us/cat/awards.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[9][5][4] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Our National Website">
<cfset aMenuItem[2] = "http://www.coldwellbanker.com/">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[9][5][5] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Careers">
<cfset aMenuItem[2] = "/default.cfm/page/about_us/cat/careers.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[9][5][6] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Find a Realtor">
<cfset aMenuItem[2] = "/default.cfm/page/agent.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[9][5][7] = aMenuItem>
<cfset aMenuItem = []>
<cfset aMenuItem[1] = "Find an Office">
<cfset aMenuItem[2] = "/default.cfm/page/offices.htm">
<cfset aMenuItem[3] = "">
<cfset aMenuItem[4] = "">
<cfset aMenu[9][5][8] = aMenuItem>
